name: todo
description: A new Flutter project.
publish_to: 'jmf'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.20
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  flutter_slidable: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

